method: bayes  # You can also use 'grid' or 'random'
metric:
  name: Performance/Composite_Score  # Combined reward and distance metric
  goal: maximize

parameters:
  batch_size:
    values: [32, 64, 128, 256, 512]
  clip_range:
    values: [0.1, 0.2, 0.3]
  ent_coef:
    values: [0, 0.0001, 0.001, 0.01]
  gae_lambda:
    distribution: uniform
    min: 0.9
    max: 1.0
  gamma:
    distribution: uniform
    min: 0.8
    max: 0.9997
  learning_rate:
    values: [0.000003, 0.00003, 0.0003, 0.003]
  log_std_init:
    values: [-1, 0, 1, 2, 3]
  n_epochs:
    values: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
  n_steps:
    values: [512, 1024, 2048, 4096]
  normalize_advantage:
    values: [True, False]
  target_kl:
    values: [0.03, 0.003]
  vf_coef:
    values: [0.5, 1]