services:


  # Grafana Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - nm-ai-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    networks:
      - nm-ai-network
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    volumes:
      # Mount the host's root filesystem
      - "/:/host:ro,rslave"
    command:
      # Point node-exporter to the mounted filesystem
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    networks:
      - nm-ai-network
    restart: unless-stopped


volumes:
  grafana-storage: {}

networks:
  nm-ai-network:
    driver: bridge