_wandb:
    value:
        cli_version: 0.21.0
        e:
            hrns33znuzo8iz9uh0xcdioehb4m1xvj:
                args:
                    - --rounds
                    - "10000"
                codePath: DM-i-AI-2025/race-car/train_ppo_real.py
                codePathLocal: DM-i-AI-2025/race-car/train_ppo_real.py
                cpu_count: 56
                cpu_count_logical: 56
                disk:
                    /:
                        total: "479342551040"
                        used: "25525379072"
                email: ludvigho@stud.ntnu.no
                executable: /cluster/home/chrisfjo/NM-ai/norwegian-ai-championship-2025/.venv/bin/python3
                git:
                    commit: ca70c204f8370636b4669719c60074508e56bbe7
                    remote: git@github.com:CogitoNTNU/norwegian-ai-championship-2025.git
                host: idun-03-01
                memory:
                    total: "269345304576"
                os: Linux-5.14.0-427.13.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /cluster/home/chrisfjo/NM-ai/norwegian-ai-championship-2025/DM-i-AI-2025/race-car/train_ppo_real.py
                python: CPython 3.11.13
                root: /cluster/home/chrisfjo/NM-ai/norwegian-ai-championship-2025
                slurm:
                    cluster_name: idun
                    conf: /var/slurm_spool/conf-cache/slurm.conf
                    cpus_on_node: "30"
                    cpus_per_task: "30"
                    gtids: "0"
                    job_account: studiegrupper-cogito
                    job_cpus_per_node: "30"
                    job_end_time: "1754157777"
                    job_gid: "13401"
                    job_id: "22979059"
                    job_name: RL-carRacing
                    job_nodelist: idun-03-01
                    job_num_nodes: "1"
                    job_partition: CPUQ
                    job_qos: normal
                    job_start_time: "1754146977"
                    job_uid: "1349963"
                    job_user: chrisfjo
                    jobid: "22979059"
                    localid: "0"
                    mem_per_node: "8192"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: idun-03-01
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /cluster/home/chrisfjo/NM-ai/norwegian-ai-championship-2025
                    submit_host: idun-login1
                    task_pid: "2622379"
                    tasks_per_node: "1"
                    topology_addr: ibsw03.idun-03-01
                    topology_addr_pattern: switch.node
                    tres_per_task: cpu=30
                startedAt: "2025-08-02T15:03:25.927661Z"
                writerId: hrns33znuzo8iz9uh0xcdioehb4m1xvj
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 15
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
algorithm:
    value: PPO
environment:
    value: real_race_car_batch_game
game_duration_seconds:
    value: 60
games_per_batch:
    value: 3
learning_rate:
    value: 0.0003
n_envs:
    value: 4
reward_threshold:
    value: 600
total_timesteps:
    value: 36000000
