name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write

jobs:
  build-and-test:
    name: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true

      - name: Run pre-commit hooks (optional)
        run: |
          uv pip install pre-commit
          pre-commit run --all-files || true
        continue-on-error: true

      - name: Install and test RAG project
        run: |
          cd rag
          uv sync --locked --all-extras
          # Run any RAG-specific tests if they exist
          if [ -f "test_pipeline.py" ]; then
            uv run python test_pipeline.py || true
          fi

      - name: Install and test Race-Car project
        run: |
          cd race-car
          uv sync --locked --all-extras
          # Run any race-car specific tests if they exist
          
      - name: Install and test Segmentation project
        run: |
          cd segmentation
          uv sync --locked --all-extras
          # Run any segmentation specific tests if they exist

      - name: Run root tests
        run: |
          if [ -d "test" ]; then
            # Install pytest if needed
            uv pip install pytest pytest-cov
            python -m pytest test/ || true
          fi

  dependabot:
    name: 'Dependabot'
    needs: [build-and-test] 
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} 
    steps:
      - name: Enable auto-merge for Dependabot PRs
        # Uses Github CLI to automatically merge the PR if test passes
        run: gh pr merge --auto --merge "$PR_URL" 
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}